[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 120

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
